#!/bin/bash
cd /home/jw/src/jmcap/ohlc

rm _*

cd logs && echo "" > ohlc.log
cd /home/jw/src/jmcap/ohlc
cd records && rm *
cd /home/jw/src/jmcap/ohlc
rm results.*

#zip *order* archive.zip
#rm *order*
mysql -ujmc -p6kjahsijuhdxhgd jmcap -e "delete from orders" # where session is not null"
rm -rf __pycache__
rm nohup.out
clear

cat<<EOF

./liveview.py -f state_0.json -c pnl_record &
./liveview.py -f state_0.json -c pct_record &
./liveview.py -f state_0.json -c pct_gain &
tail -f logs/ohlc.log &
tail -f /var/lib/mysql/jw-box.log &


./pread.py -f records/B_1635635380.ord
./pread.py -f records/B_1635635380.ord.r_0
mysql -ujmc -p6kjahsijuhdxhgd jmcap -e "SELECT SUM(orders.price * orders.size)  as totcost, orders.price,  sum(orders.size),orders.side FROM orders group by orders.side;"

EOF



./ohlc.py --clear --batch

