0 = 0
offline = true
datatype = "backtest"
datalength = 39_999
backtestfile = "long.json"
backtestmeta = "long_DATA.json"
pair = "ETH/BTC"
capital = 1
purch_pct = 10
timeframe = "5m"
startdate = "2021-02-05 18:10:00"
maxbuys = 10
purch_qty_adj_pct = 30
columns = 2
mysql = true
display = true
rt_id = 0
interval = 10
figsize = [ 6, 4 ]
csvname = "results.csv"
datadir = "/home/jw/src/jmcap/ohlc/data"
datawindow = 28
since = "24:h"
convert_price = true
offline_price = 64_000
price_conversion = "BTC/USD"
bbcolors = [ "red", "green", "blue" ]
bblengths = [ 12, 17, 23 ]
bbstd = [ 2.1, 2.0, 1.9 ]
bb2lengths = [ 12, 17, 23 ]
bb2std = [ 2.1, 2.0, 1.9 ]
BBbasis = "Close"
BB2basis = "siglf"
tholo_span = 52
volumeline_span = 5
volumelines = true
MACD_src = "Close"
EMA_fast = 12
EMA_slow = 26
signal_span = 9
ffmap_span = 2
bw_filter = "bp"
lowpctline = 15
loc_plots_rohlc = 1
plots_rohlc = true
loc_plots_ema = 5
plots_ema = true
plots_ema_hide = true
loc_plots_volume = 4
plots_volume = true
loc_plots_bbavg = 0
plots_bbavg = true
loc_plots_bb_1 = 0
plots_bb_1 = true
loc_plots_bb_2 = 0
plots_bb_2 = true
loc_plots_bb_3 = 0
plots_bb_3 = true
loc_plots_macd = 5
plots_macd = true
loc_plots_sigffmb = 2
plots_sigffmb = true
plots_sigffmb_hide = true
loc_plots_sigffmap = 2
plots_sigffmap = true
loc_plots_sigffmb2 = 2
plots_sigffmb2 = true
plots_sigffmb2_hide = true
loc_plots_sigffmap2 = 2
plots_sigffmap2 = true
loc_trigger = 0
cooldown = 2
testpair = [ "BUY_CltLowBbavg", "SELL_HgtHiBbavg_ffmapLowCoA" ]
triggers = true
closeXn = 1.01
delta_highlimit_sell = 0.2
delta_lowlimit_buy = -0.2
pt1_highlimit_sell = 0.2
pt1_lowlimit_buy = -0.2
overunder_sell = 0.2
overunder_buy = -0.2
fill = true
seed = 99
mu = 0.0001
sigma = 0.008
spread = 0.02
save = true
epoch_ms_delta = 60_000
logging = 20

[creds]
name = "coinbase_sandbox"
provider = "coinbase"
apitype = "sandbox"
api_url = "api-public.sandbox.pro.coinbase.com"

[bb_ewm_length]
lower = 10
middle = 10
upper = 10

[filter]
ffmx = 1_000
lfmx = 1_000

  [filter.hp]
  name = "highpass"
  N = 4
  Wn = 0.08

  [filter.lp]
  name = "lowpass"
  N = 2
  Wn = 0.1

  [filter.bp]
  name = "bandpass"
  N = 4
  Wn = [ 0.19, 0.21 ]

  [filter.bs]
  name = "bandstop"
  N = 4
  Wn = [ 0.3, 0.4 ]

[mbpfilter]
name = "bandpass"
N = 1
mx = [ 12.0, 4.0, 2.4, 1.714, 1.333, 1.091 ]
Wn = [
  [ 0.000001, 0.166667 ],
  [ 0.166667, 0.333333 ],
  [ 0.333333, 0.5 ],
  [ 0.5, 0.666667 ],
  [ 0.666667, 0.833333 ],
  [ 0.833333, 0.999999 ]
]

[deptree.deltadelta]
hilodelta = true
opcldelta = true

[deptree.bbavg]
bb_1 = true
bb_2 = true
bb_3 = true

[deptree.2_bbavg]
2_bb_1 = true
2_bb_2 = true
2_bb_3 = true

[deptree.macd]
ema = true

[deptree.tholo]
hilodelta = true

[overunder1style]
color = "red"
width = 1
alpha = 1

[overunder2style]
color = "green"
width = 1
alpha = 1

[overunder3style]
color = "blue"
width = 1
alpha = 1

[bbuAvgstyle]
color = "yellow"
width = 1
alpha = 0.3

[bbmAvgstyle]
color = "magenta"
width = 1
alpha = 0.3

[bblAvgstyle]
color = "cyan"
width = 1
alpha = 0.3

[bb1style]
color = "red"
width = 1
alpha = 0.3

[bb2style]
color = "green"
width = 1
alpha = 0.3

[bb3style]
color = "blue"
width = 1
alpha = 0.3

[bbu2Avgstyle]
color = "orange"
width = 1
alpha = 1

[bbm2Avgstyle]
color = "magenta"
width = 1
alpha = 1

[bbl2Avgstyle]
color = "cyan"
width = 1
alpha = 1

[bb21style]
color = "red"
width = 1
alpha = 1

[bb22style]
color = "green"
width = 1
alpha = 1

[bb23style]
color = "blue"
width = 1
alpha = 1

[hilostyle]
color = "blue"
width = 2
alpha = 1

[hilodeltastyle]
color = "blue"
width = 2
alpha = 1

[opcldeltastyle]
color = "grey"
width = 4
alpha = 1

[deltadeltastyle]
color = "green"
width = 1
alpha = 1

[volclrupstyle]
color = "green"
width = 2
alpha = 1

[volclrdnstyle]
color = "red"
width = 0.5
alpha = 0.7

[tholostyle_V]
color = "blue"
width = 1
alpha = 1

[tholostyle_I]
color = "red"
width = 1
alpha = 1

[tholostyle_R]
color = "green"
width = 1
alpha = 1

[tholostyle_S]
color = "cyan"
width = 1
alpha = 1

[pt1style]
color = "pink"
width = 4
alpha = 0.3

[normclosestyle]
color = "blue"
width = 4
alpha = 0.3

[MACDstyle]
color = "orange"
width = 1
alpha = 1

[siglinstyle]
color = "blue"
width = 1
alpha = 1

[histogramstyle]
color = "purple"
width = 1
alpha = 1

[overunderstyle]
color = "purple"
width = 1
alpha = 1

[siglfstyle]
color = "green"
width = 1
alpha = 1

[sigffstyle]
color = "purple"
width = 1
alpha = 1

[sigffmbstyle]
color = [ "red", "olive", "blue", "cyan", "magenta", "green" ]
width = 1
alpha = 1

[sigffmb2style]
color = [ "red", "olive", "blue", "cyan", "magenta", "green" ]
width = 1
alpha = 1

[ffmapstyle]
color = "green"
width = 1
alpha = 1

[ffmaplolimstyle]
color = "green"
linewidth = 1
alpha = 1

[ffmaphilimstyle]
color = "green"
linewidth = 1
alpha = 0.3

[ffmap2style]
color = "red"
width = 1
alpha = 1

[ffmap2lolimstyle]
color = "red"
linewidth = 1
alpha = 1

[ffmap2hilimstyle]
color = "red"
linewidth = 1
alpha = 0.3

[rohlcstyle]
color = "purple"
width = 1
alpha = 1

[[mavs]]
length = 10
color = "violet"
width = 2
alpha = 1

[[mavs]]
length = 20
color = "brown"
width = 2
alpha = 1

[[mavs]]
length = 30
color = "red"
width = 2
alpha = 1
