#!/bin/python
import os,sys,getopt
import time
# import lib_globals as g
import pprint as pp
import json

ndir = False

argv = sys.argv[1:]
try:
    opts, args = getopt.getopt(argv, "-hd:", ["help","dir="])
except getopt.GetoptError as err:
    sys.exit(2)

for opt, arg in opts:
    if opt in ("-h", "--help"):
        print("-h, --help   this info")
        print("-d, --dir  in /home/jw/src/jmcap")
        sys.exit(0)

    if opt in ("-d", "--dir"):
        ndir = arg

import lib_ohlc as o

fndir = f"/home/jw/src/jmcap/{ndir}"
print(f"IN DIRECTIRY:: {fndir}")

print(f"deleting {fndir}")
os.system(f"rm -rf {fndir}")

print(f"mkdir {fndir}")
os.makedirs(fndir, exist_ok=True)
os.system(f"./mkLIVE {fndir} C")

os.system(f"cp config_{ndir}.hcl {fndir}/config_0.hcl")


# cmd = f'terminator -e > /dev/null 2>&1 "cd {fndir} && ./CLEANRUN -c -b"'
cmd = f'terminator -e > /dev/null 2>&1 "cd {fndir} && /bin/zsh"'
print(cmd)
print("------------------------------------------------------")
os.system(cmd)

